# Generated by Django 6.1.1 on 2026-10-04 09:56

# Store account-specific dashboard choices without changing extracted notice records.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_documentupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='myapp.actionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_action_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'action_item'), name='unique_student_action_state')],
            },
        ),
        migrations.CreateModel(
            name='StudentDateState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='myapp.documentdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_date_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'document_date'), name='unique_student_date_state')],
            },
        ),
    ]
