# Generated by Django 6.1.1 on 2026-10-04 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studentactionstate_studentdatestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_plan_items', to='myapp.actionitem')),
                ('document_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_plan_items', to='myapp.documentdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_plan_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('planned_date', 'created_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('action_item__isnull', False)), fields=('user', 'action_item'), name='unique_student_plan_action')],
            },
        ),
    ]
